name: result_controller
description: "Functional error handling with Result pattern. Safely manage operations that can fail, with clean, type-safe error control."

version: 1.3.0
homepage: https://github.com/JhonaCodes/result_controller
topics:
  - result
  - error-handling
  - functional-programming
  - state-management
  - dart


platforms:
  linux:
  macos:
  windows:
  web:
  android:
  ios:

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:

dev_dependencies:
  # Testing
  test: ^1.25.6

  # Linting and analysis
  lints: ^6.0.0
